version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: gcr.io/lnd-249718/github.com/z1nkum/btcd:latest
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - EXTERNAL_ADDRESS

    btcd:
        extends: btc
        container_name: btcd
        restart: always
        ports:
          - "18333:18333"
          - "18334:18334"
          - "8333:8333"
          - "8334:8334"
        environment:
          - DEBUG
          - MINING_ADDRESS
          - NETWORK
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]


    lnd_btc:
      image: gcr.io/lnd-249718/github.com/z1nkum/lnd:latest
      restart: always
      environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - EXTERNAL_ADDRESS
          - ALIAS
      container_name: lnd_btc
      ports:
          - "9735:9735"
          - "10009:10009"
      volumes:
          - shared:/rpc
          - /root/.lnd:/root/.lnd/data:rw
      links:
          - "btcd:blockchain"
      entrypoint: ["./start-lnd.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local